#RAILWAY APP CONFIG
#spring:
#  datasource:
#    url: jdbc:mysql://containers-us-west-2.railway.app:6718/railway?useSSL=false
#    username: root
#    password: wyz9c7RIHelDE9G8W3lM

#LOCALHOST APP CONFIG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zeraki?useSSL=false
    username: root
    password:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  #  jpa:
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL5Dialect

  #JPA Settings
  jpa.hibernate.ddl_auto: update